workKFC/Models/ErrorViewModel.cs
namespace workKFC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

workKFC/Models/customer.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class customer
{
    [Key]
    [DisplayName("編號")]
    public int id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("帳號")]
    public string account { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("密碼")]
    public string password { get; set; }

    [StringLength(30)]
    [DisplayName("姓名")]
    public string name { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("電話")]
    public string tel { get; set; }

    [StringLength(50)]
    [DisplayName("地址")]
    public string address { get; set; }
}

workKFC/Models/meals.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class meals
{
    [Key]
    [StringLength(5)]
    [Unicode(false)]
    [DisplayName("編號")]
    public string num { get; set; }

    [StringLength(50)]
    [DisplayName("餐點名稱")]
    public string title { get; set; }
    [DisplayName("價格")]
    public int? price { get; set; }

    [StringLength(30)]
    [DisplayName("圖片")]
    public string img { get; set; }
}

workKFC/Models/orders.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class orders
{
    [Key]
    [DisplayName("編號")]
    public int id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("訂單編號")]
    public string ordersnum { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("帳號")]
    public string account { get; set; }
    [DisplayName("日期")]
    public DateTime? orderdate { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    [DisplayName("餐點編號")]
    public string mealnum { get; set; }

    [StringLength(50)]
    [DisplayName("餐點名稱")]
    public string mealtitle { get; set; }
    [DisplayName("數量")]
    public int? qty { get; set; }
    [DisplayName("單價")]
    public int? price { get; set; }
    [DisplayName("小計")]
    public int? total { get; set; }
}

workKFC/Models/workKFCContext.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class workKFCContext : DbContext
{
    public workKFCContext(DbContextOptions<workKFCContext> options)
        : base(options)
    {
    }

    public workKFCContext()
    {

    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=workKFC;Trusted_Connection=True;TrustServerCertificate=true;MultipleActiveResultSets=true;");
        }
    }

    public virtual DbSet<customer> customer { get; set; }

    public virtual DbSet<meals> meals { get; set; }

    public virtual DbSet<orders> orders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<customer>(entity =>
        {
            entity.Property(e => e.tel).IsFixedLength();
        });

        modelBuilder.Entity<orders>(entity =>
        {
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

workKFC/Controllers/BackController.cs
using Microsoft.AspNetCore.Mvc;
using workKFC.Models;

namespace workKFC.Controllers
{
    public class BackController : Controller
    {
        workKFCContext db = new workKFCContext();
        public IActionResult Index()
        {
            var meals = db.meals.ToList();
            return View(meals);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(string num, string title, int price, IFormFile photo)
        {
            //上傳圖檔
            string fileName = "";
            //檔案上傳
            if (photo != null)
            {
                if (photo.Length > 0)
                {
                    string filePath = "wwwroot/images/" + photo.FileName;
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        //程式寫入的本地資料夾裡面
                        await photo.CopyToAsync(stream);
                    }
                }

            }
            meals m = new meals();
            m.num = num;
            m.title = title;
            m.price = price;
            m.img = photo.FileName;
            db.meals.Add(m);
            db.SaveChanges();

            return RedirectToAction("Index", "Back");  //轉向Index首頁
        }

        //修改
        public ActionResult Edit(string id)
        {
            //先查出這筆記錄           
            var data = db.meals.Where(m => m.num == id).FirstOrDefault();
            //暫存至ViewBag,表單欄位可以顯示出來        
            ViewBag.name = data.title;
            ViewBag.price = data.price;
            ViewBag.img = data.img;
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string num, string title, int price, IFormFile photo)
        {
            //先找到這筆記錄
            var data = db.meals.Where(m => m.num == num).FirstOrDefault();
            //上傳圖檔
            string fileName = "";
            //檔案上傳
            if (photo != null)
            {
                if (photo.Length > 0)
                {
                    string filePath = "wwwroot/images/" + photo.FileName;
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        data.img = photo.FileName;   //圖片檔名
                        //程式寫入的本地資料夾裡面
                        await photo.CopyToAsync(stream);
                    }
                }
            }
            data.title = title;
            data.price = price;
            db.SaveChanges();
            return RedirectToAction("index", "Back");
        }

        public ActionResult Delete(string id)
        {
            var data = db.meals.Where(m => m.num == id).FirstOrDefault();
            db.meals.Remove(data);
            db.SaveChanges();
            return RedirectToAction("index", "Back");
        }

    }

}

workKFC/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;
using workKFC.Models;
using X.PagedList;
using X.PagedList.Extensions;



namespace workKFC.Controllers
{
    public class pageController : Controller
    {
        workKFCContext db=new workKFCContext();
        int pageSize = 4;
        public IActionResult Index(int page = 1)
        {
            int currentPage = page < 1 ? 1 : page;
            var products = db.meals.OrderBy(m => m.num).ToList();
            var result = products.ToPagedList(currentPage, pageSize);
            return View(result);

        }
    }

}

workKFC/Controllers/TypeController.cs
using Microsoft.AspNetCore.Mvc;
using workKFC.Models;

namespace workKFC.Controllers
{
    public class TypeController : Controller
    {
        workKFCContext db=new workKFCContext();
        public IActionResult Index(int id=1)
        {
            if (id == 1)
                ViewBag.name = "套餐";
            else if (id == 2)
                ViewBag.name = "蛋塔盒";
            else if (id == 3)
                ViewBag.name = "桶餐";
            else
                ViewBag.name = "飲料其它";
            var data = db.meals.Where(m => m.num.Substring(1, 1).Equals(id + "")).ToList();

            return View(data);

        }
    }
}

workKFC/Views/Back/Create.cshtml
@model workKFC.Models.meals

@{
    ViewData["Title"] = "餐點建檔";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}
<h1>餐點建檔</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
          
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="num" class="control-label"></label>
                <input asp-for="num" class="form-control" />
                <span asp-validation-for="num" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                請選擇要上傳的檔案:
                <p><input type="file" name="photo" id="photo" /></p>
            </div>
            <p>&nbsp;</p>
            <div class="form-group">
                <input type="submit" value="新增" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">回首頁</a>
</div>

workKFC/Views/Back/Edit.cshtml
@model workKFC.Models.meals

@{
    ViewData["Title"] = "修改";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}

<h1>修改</h1>

<hr />
<div class="row">
    <div class="col-md-4">
     <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="num" />
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control"  value="@ViewBag.name" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" value="@ViewBag.price" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                圖片(沒有傳以舊圖為主):
                <p><input type="file" name="photo" id="photo" value="@ViewBag.img" /></p>
            </div>
            <p>&nbsp;</p>
            <div class="form-group">
                <input type="submit" value="修改" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">回首頁</a>
</div>

workKFC/Views/Back/Index.cshtml
@model IEnumerable<workKFC.Models.meals>

@{
    ViewData["Title"] = "肯德基點餐--後台首頁";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}

<h1>肯德基點餐--後台首頁</h1>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="thumbnail">
                <img src="~/images/@item.img" style="width:70%">
                <div class="caption">
                    <h2>@item.title</h2>
                    <p>單價：@item.price</p>
                    <p>
                        <a href="@Url.Action("Edit")?id=@item.num" class="btn btn-primary">修改</a>
                        <a href="@Url.Action("Delete")?id=@item.num" class="btn btn-primary" onclick="return confirm('確定刪除嗎？');">刪除</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

workKFC/Views/Home/Index.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@model IEnumerable<workKFC.Models.meals>
@{
    ViewData["Title"] = "麥當當餐點";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <p></p>
    @ViewBag.myaccount
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="thumbnail">
                <img src="~/images/@item.img" style="width:70%">
                <div class="caption">
                    <h2>@item.title</h2>
                    <p>單價：@item.price</p>
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("account") == null)
                    {
                        <p></p>
                    }
                    else
                    {
                        <p><a href="@Url.Action("AddCar")?mNum=@item.num" class="btn btn-primary">加入購物車</a></p>
                    }
                </div>
            </div>
        </div>
    }
</div>

workKFC/Views/Home/Login.cshtml
@{
    ViewBag.Title = "會員登入";
}

<h2>會員登入</h2>

<form action="@Url.Action("Login")" method="post">
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <span class="control-label col-md-2">帳號</span>
            <div class="col-md-2">
                <input type="text" id="account" name="account" required="required" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <span class="control-label col-md-2">密碼</span>
            <div class="col-md-2">
                <input type="password" id="password" name="password" required="required" class="form-control" />
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="登入" class="btn btn-primary" />
                @ViewBag.Message
            </div>
        </div>
    </div>
</form>

workKFC/Views/Home/Meals.cshtml
@model IEnumerable<workKFC.Models.meals>
@{
    ViewData["Title"] = "麥當當餐點";
    Layout = "~/Views/Shared/_LayoutMember.cshtml";
}
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="thumbnail">
                <img src="~/images/@item.img" style="width:70%">
                <div class="caption">
                    <h2>@item.title</h2>
                    <p>單價：@item.price</p>
                    <p><a href="@Url.Action("AddCar")?mNum=@item.num" class="btn btn-primary">加入購物車</a></p>
                </div>
            </div>
        </div>
    }
</div>

workKFC/Views/Home/register.cshtml
@model workKFC.Models.customer

@{
    ViewData["Title"] = "註冊";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>註冊</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="account" class="control-label"></label>
                <input asp-for="account" class="form-control" />
                <span asp-validation-for="account" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" type="password" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tel" class="control-label"></label>
                <input asp-for="tel" class="form-control" />
                <span asp-validation-for="tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="註冊" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">回首頁</a>
</div>

workKFC/Views/Home/showCar.cshtml
@model IEnumerable<workKFC.Models.orders>
@{
    ViewData["Title"] = "showCar";
    Layout = "~/Views/Shared/_LayoutMember.cshtml";
}

<h1>訂單</h1>
<table class="table table-bordered" >
    <thead>
        <tr>
            <th>圖片</th>
            <th>
                @Html.DisplayNameFor(model => model.ordersnum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.account)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.orderdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mealnum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mealtitle)
            </th>
                        <th>
                @Html.DisplayNameFor(model => model.qty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
<img src="~/images/@{
@Html.DisplayFor(modelItem => item.mealnum)
}.jpg" width="50%"  />
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.ordersnum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.account)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.orderdate)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mealnum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mealtitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.qty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total)
                </td>
                <td>
                    <a href="@Url.Action("Delete")?mNum=@item.mealnum" onclick="return confirm('確定刪除嗎？');" class="btn btn-warning">刪除</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<hr />
<h3>總計:@ViewBag.sum</h3>

workKFC/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -肯德基點餐</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/workKFC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">肯德基點餐</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class=nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首頁</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">登入</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="register">註冊</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - 肯德基餐點-<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

workKFC/Views/Shared/_LayoutBack.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -肯德基點餐--後台</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/workKFC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">肯德基點餐</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class=nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">前台首頁</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Back" asp-action="Index">後台首頁</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Back" asp-action="Create">餐點建檔</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - 肯德基餐點-<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

workKFC/Views/Shared/_LayoutMember.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -肯德基點餐</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/workKFC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">肯德基點餐</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
      <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Meals">餐點</a>
          </li>
          <li class="nav-item">
               <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="showCar">訂單</a>
           </li>
          <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">登出</a>
           </li>
          <li class="nav-item">
             <span class="nav-link text-dark"> @HttpContextAccessor.HttpContext.Session.GetString("account")歡迎光臨</span>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - 肯德基餐點-<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

workKFC/Views/Type/Index.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@model IEnumerable<workKFC.Models.meals>
@{
    ViewData["Title"] = "麥當當餐點";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>麥當當餐點</h1>

<div class="row">
    <p></p>
    <div style="font-size:x-large">
        <form method="post" action="@Url.Action("Index","Type")">
            <select name="id">
                <option value="1">套餐</option>
                <option value="2">蛋塔盒裝</option>
                <option value="3">桶餐</option>
                <option value="3">飲料點心</option>
            </select>
            <input type="submit" value="查詢" />
        </form>
    </div>
    <p></p>
    <h2>@ViewBag.name</h2>
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="thumbnail">
                <img src="~/images/@item.img" style="width:50%">
                <div class="caption">
                    <h2>@item.title</h2>
                    <p>單價：@item.price</p>
                    @if (HttpContextAccessor.HttpContext.Session.GetString("account") == null)
                    {
                        <p></p>
                    }
                    else
                    {
                        <p><a href="@Url.Action("AddCar")?mNum=@item.num" class="btn btn-primary">加入購物車</a></p>
                    }
                </div>
            </div>
        </div>
    }
</div>

workKFC/Views/page/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList
@model IPagedList<workKFC.Models.meals>
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewBag.Title = "麥當當餐點";
}
<link href="~/css/PagedList.css" rel="stylesheet" />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="thumbnail">
                <img src="~/images/@item.img" style="width:50%">
                <div class="caption">

                    <h2>@item.title</h2>
                    <p>單價：@item.price</p>
                    @if (HttpContextAccessor.HttpContext.Session.GetString("account") == null)
                    {
                        <p></p>
                    }
                    else
                    {
                        <p><a href="@Url.Action("AddCar")?mNum=@item.num" class="btn btn-primary">加入購物車</a></p>
                    }
                </div>
            </div>
        </div>
    }
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", "Page", new { page }))